#ifndef INITFLAGS_H
#define INITFLAGS_H

const bool retrieveDesktopDebug = false;
const bool preprocessDebug = false;
const bool flatfieldDebug = false;
/* DONE
#DEFINES += "RETRIEVEDESKTOP_DEBUG"
#DEFINES += "PREPROCESS_DEBUG"
#DEFINES += "FLATFIELD_DEBUG"
*/
/* NOT YET DONE
#DEFINES += "DEBUG"
#DEFINES += "TOGRAYSCALE_DEBUG"
#DEFINES += "SETGRAYFRAME_DEBUG"
#DEFINES += "GETGRAYFRAME_DEBUG"
#DEFINES += "DETECTFACES_DEBUG"
#DEFINES += "FINDNEWFACES_DEBUG"
#DEFINES += "DETECTUPPERBODY_DEBUG"
#DEFINES += "PROCESSFACEDATA_DEBUG"
#DEFINES += "SETFACEROI_DEBUG"
#DEFINES += "MAKEEMPIRICEYES_DEBUG"
#DEFINES += "SETEMPIRICEYES_DEBUG"
#DEFINES += "GREATCATCH_DEBUG"
#DEFINES += "GREATCATCH_TEST"
#DEFINES += "FINDPUPILS_DEBUG"
#DEFINES += "FINDPUPILS_WINDOWS"
#DEFINES += "FINDPUPILS_TEST"
#DEFINES += "DARKCROSS_DEBUG"
#DEFINES += "CLEARPUPILS_DEBUG"
#DEFINES += "SHOWPUPILS_DEBUG"
#DEFINES += "SETLEFTPUPIL_DEBUG"
#DEFINES += "SETRIGHTPUPIL_DEBUG"
#DEFINES += "FOLLOWGAZE_DEBUG"
#DEFINES += "EVALUATEGAZE_DEBUG"
#DEFINES += "ESTIMATEANDSHOWGAZESTARTINGPOINT_DEBUG"
#DEFINES += "COMPUTEFINALGAZEX_DEBUG"
#DEFINES += "TRACKGAZE_DEBUG"
#DEFINES += "EXPONENTIALAPPROX_DEBUG"
#DEFINES += "LINEARAPPROX_DEBUG"
#DEFINES+= "UPHOLSTER_DEBUG"
#DEFINES+= "UPHOLSTER_WINDOWS"
#DEFINES += "KETROD_DEBUG"
#DEFINES += "REFINEPUPILS_DEBUG"
#DEFINES += "WEBSERVICE"
DEFINES += "ACTIVE_CAM"
#DEFINES += "TEST_MODE"
#DEFINES += "AUTOMATIC_TEST"
#DEFINES += "ONLY_REAL_PUPIL"
*/

#endif // INITFLAGS_H
